
https-portal:
  image: steveltn/https-portal:1
  ports:
    - '80:80'
    - '443:443'
  links:
    - nginx
  environment:
    DOMAINS: 'pfaulk.de -> http://nginx:80'
nginx:
  ports:
    - '80:80'
  image: nginx

